services:
    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        env_file: docker.env
        environment:
            MYSQL_ROOT_PASSWORD: DATABASE_PASSWORD
            MYSQL_DATABASE: DATABASE_NAME
            MYSQL_USER: DATABASE_USER
            MYSQL_PASSWORD: DATABASE_PASSWORD
        ports:
            - '3307:3306'
        volumes:
            - db_data:/var/lib/mysql

    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django_app
        restart: always
        depends_on:
            - db
        env_file: docker.env
        environment:
            DATABASE_NAME: DATABASE_NAME
            DATABASE_USER: DATABASE_USER
            DATABASE_PASSWORD: DATABASE_PASSWORD
            DATABASE_HOST: db
            DATABASE_PORT: 3306
            NPM_BIN_PATH: NPM_BIN_PATH
        ports:
            - '8000:8000'

volumes:
    db_data:
