# Generated by Django 5.1 on 2024-11-10 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_end_date_alter_record_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawnshop',
            name='user',
        ),
        migrations.AlterField(
            model_name='record',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 2, 53, 50, 568142, tzinfo=datetime.timezone.utc)),
        ),
    ]
