# Generated by Django 5.1 on 2024-11-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_record_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='pawnshop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.pawnshop'),
            preserve_default=False,
        ),
    ]
