# Generated by Django 5.1 on 2024-11-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_pawnshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawnshop',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='pawnshop',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
