# Generated by Django 5.1 on 2024-11-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_pawnshop_description_alter_pawnshop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawnshop',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='pawnshop',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
