# Generated by Django 5.1 on 2024-11-18 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_resell'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='item_status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
