# Generated by Django 5.1.3 on 2024-11-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_profile'),
        ('records', '0011_record_item_status'),
    ]

    operations = [
    ]
